### ISSUE TITLE
Improvement: integrate ACME-DNS  DNS provider

### ISSUE THREAD

**Issue by pmhausen** [Monviech/os-caddy-plugin#101]
ACME DNS is a self-hosted DNS provider for certificate authorisation. Currently the Caddy plugin does not offer any self hosted solution. OPNsense's os-acme-client can use ACME DNS, too, so I propose to integrate it.

https://github.com/caddy-dns/acmedns

Kind regards,
Patrick

**Comment by Monviech** [comment]
Sure, the caddy binary already includes this plugin, just needs the GUI component and Caddyfile template component added.

**Comment by Monviech** [comment]
Oof this looks complicated. I need outlined what is exactly needed for a self hosted ACME DNS to work. I have no experience with that.

If each domain and subdomain needs an own account, this will be a huge requirement and such a big change I'm not sure I want to do it.

**Comment by Monviech** [comment]
Compare to here: https://github.com/Monviech/os-caddy-plugin/issues/84#issuecomment-1916232406

**Comment by pmhausen** [comment]
It's not that hard, really. I'm not asking to add the acme-dns backend ;)

To just **use** and acme-dns server running somewhere all you need to set are the API URL of that server and a couple of credentials. How to set up these is left as an exercise to the acme-dns admin.

Compare:
![Bildschirmfoto 2024-02-21 um 17 10 03](https://github.com/Monviech/os-caddy-plugin/assets/27051716/d5b4ba05-9679-430d-be12-168501549309)

I'll help with a pull-request, I guess.

**Comment by Monviech** [comment]
Oh so its really just those 4 fields? No problemo then, Im adding this soon.
