### ISSUE TITLE
Typo under Reverse Proxy > Handlers

### ISSUE THREAD

**Issue by therealmelee** [Monviech/os-caddy-plugin#118]
Short and sweet. 😁

The header for 'subdomain' says 'subomain' (missing the D).

![Screenshot 2024-03-03 20 39 53](https://github.com/Monviech/os-caddy-plugin/assets/56363525/593a1ff9-5b07-4947-ac54-5545dfb5f707)

**Comment by Monviech** [comment]
Thank you, fixed in 33127a3
