### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by Moe1369** [Monviech/os-caddy-plugin#127]
In my case I'd like to use this in combination with authentik.

More Infos here:
https://docs.goauthentik.io/docs/providers/proxy/server_caddy

I know I could make it work with custom configs but is there a gui way I'm not seeing?

**Comment by Monviech** [comment]
Could you give me an example Caddyfile of your configuration and which part you need exactly? If its the whole `forward_auth` and `copy_headers` part, thats not possible in the GUI right now.

**Comment by Moe1369** [comment]
Sadly it is. But thanks for confirming.

**Comment by Monviech** [comment]
The scope of this plugin is more of an "Easy to configure" reverse proxy. Adding too many things would make the GUI of it more convoluted right now. For the full feature richness there are alternatives like haproxy and nginx plugin. They offer very thorough configuration of many cases like these (probably), but they're very hard to configure for "the normal user who wants things to just work".

Hope I could help you. ^^

**Comment by Moe1369** [comment]
> The scope of this plugin is more of an "Easy to configure" reverse proxy. Adding too many things would make the GUI of it more convoluted right now. For the full feature richness there are alternatives like haproxy and nginx plugin. They offer very thorough configuration of many cases like these (probably), but they're very hard to configure for "the normal user who wants things to just work". (like me xD)
> 
> Hope I could help you. ^^

That's why I closed the issue. ^^

**Comment by Monviech** [comment]
Oh okay. I just wanted to explain myself. Thanks for raising this issue though, its interesting to see what people want. If it happens more often it can always be considered. Or somebody contributes it. :)

**Comment by Monviech** [comment]
@Moe1369 
https://github.com/opnsense/plugins/issues/3881
