### ISSUE TITLE
Help needed to create a repo from a .pkg file?

### ISSUE THREAD

**Issue by gspannu** [Monviech/os-caddy-plugin#129]
Hi @Monviech,

First of all, thanks for creating this plugin - a life saver for OPNsense users !

--- 

**Need some assistance in creating a repo from a plugin package.**

I have created a OPNsense plugin for BlockyDNS. I have it working fully within OPNsense and all works as expected. 

I created this .pkg file by running `make package` within the plugin folder of my FreeBSD development machine.
Essentially created the `src folder, Makefile, pkg-descr` in `/usr/plugins/devel/blocky` folder. Then I run `make package` from the blocky folder... and after successful execution, it creates work/pkg subfolder with the newly created `os-xxxx.pkg` file.

I can copy the os-xxxx.pkg file into OPNsense, execute `pkg add os-xxxx.pkg` and I can get _BlockyDNS working as expected_. in OPNsense, GUI and all, etc...

However, I would like to `convert this os-xxxx.pkg file to a repo` that I can host online - how do I go about creating a repo from an existing .pkg file? 

---

Essentially make this work similar to your os-caddy... by fetching a conf file, running pkg update and then being able to install it from Plugins GUI within OPNsense.

> fetch -o /usr/local/etc/pkg/repos/os-blocky-plugin.conf https://os-blocky-plugin.xxxxxx.com/repo-config/os-blocky-plugin.conf
> pkg update
> Afterwards install os-blocky from the Plugins in the OPNsense GUI. 
> 

Can you provide some help/ layman style instructions as to how to build this ?
Many thanks...

**Comment by Monviech** [comment]
I saw that you posted in the OPNsense Forum and I answered there a while ago. Lets continue this in the forum since this issue looks unrelated to this plugin.
