### ISSUE TITLE
Any mechanism to only use a custom file?

### ISSUE THREAD

**Issue by gspannu** [Monviech/os-caddy-plugin#28]
There are so many options in Caddy that making everything (other than common settings) in the GUI may become difficult ... in the long term.

**Can you look at making an option that allows 'custom contents to be written to a text container' ... but with no dependency on any GUI entries.**?
This would then allow users to write their complete custom Caddyfile in this text container (but could then leave everything in GUI blank)?

I guess, advanced users will highly use this custom feature, but would still use the plugin to enable/disable/restart the plugin and use the 'Logging' GUI to diagnose.

**Comment by Monviech** [comment]
I have implemented import statements. Is that sufficient? An advanced user could just drop them there if needed.

https://github.com/Monviech/os-caddy-plugin/blob/main/README.md#custom-configuration-files

**Comment by gspannu** [comment]
> I have implemented import statements. Is that sufficient? An advanced user could just drop them there if needed.
> 
> https://github.com/Monviech/os-caddy-plugin/blob/main/README.md#custom-configuration-files
> 
> https://github.com/Monviech/os-caddy-plugin/blob/3cb345805eb5895cbf7befa8361e6130606863b7/usr/plugins/devel/caddy/src/opnsense/service/templates/Pischem/Caddy/Caddyfile#L28-L29
> 
> https://github.com/Monviech/os-caddy-plugin/blob/3cb345805eb5895cbf7befa8361e6130606863b7/usr/plugins/devel/caddy/src/opnsense/service/templates/Pischem/Caddy/Caddyfile#L49-L50

That would work... **as long as there is nothing in the GUI that is mandatory** that may break the final caddyfile.
If the user left everything in the GUI blank, just created the custom *.conf file (_as an example, what I have pasted in my earlier comment_), then just used the GUI to enable/ disable the service and used the GUI logging to view logs.

If this works.. then I guess nothing more is needed.

**Comment by gspannu** [comment]
> Yeah the GUI has no mandatory fields. The only mandatory things that will be generated can be seen in the Caddyfile template, mostly related to default file storage and logging. It can just be enabled in the GUI and thats it. I especially made sure there are imports so there don't have to be any hacky workarounds.
> 
> The only thing the user has to make sure of, is that global options are in .global files, and nonglobal options are in .conf files.
> 
> There's also an automatic "caddy fmt --overwrite" to fix wrong formatting when the service restarts. https://caddyserver.com/docs/command-line#caddy-fmt

👍 
I’ll start testing in a few days… just tied up with work/ travel for now.

**Comment by Monviech** [comment]
@gspannu Thanks, looking forward to your tests. Probably won't even need the custom files anymore now since everything can be set in the GUI. You can even set nested handles in subdomains.

**Comment by gspannu** [comment]
> @gspannu Thanks, looking forward to your tests. Probably won't even need the custom files anymore now since everything can be set in the GUI. You can even set nested handles in subdomains.

**I haven’t looked at your latest release (yet).**

Will do in a few days, travelling for work, so a bit busy.

_As a quick question, does the handles implementation allow for a custom cert (rather than obtain from LetsEncrypt)… e.g._

I know it supports this…
```
*.example.com:443 {
        tls {
                dns cloudflare 1484053787dJQB8vP1q0yc5ZEBnH6JGS4d3mBmvIeMrnnxFi3WtJdF
        }
        @bar.example.com host bar.example.com
        handle @bar.example.com {
                reverse_proxy 192.168.1.1:443
        }
```

But would it support this as well?
```
*.example.com:443 {
        tls /var/etc/myowncustomcert.pem /var/etc/myowncustomkey.pem  #Using self provided certificate

        @bar.example.com host bar.example.com
        handle @bar.example.com {
                reverse_proxy 192.168.1.1:443
        }
```

**Comment by Monviech** [comment]
No it doesn't support that yet, for that you need custom configuration. I mean something like a certificate field exists in the standard field types of OPNsense and could be maybe imolemented,. I wanne do a feature freeze right now though until the current stuff is all tested. https://docs.opnsense.org/development/frontend/models_fieldtypes.html#certificatefield

**Comment by Monviech** [comment]
https://github.com/Monviech/os-caddy-plugin/pull/37
Implemented it.

**Comment by Monviech** [comment]
@gspannu
I wanted to thank you for all the suggestions that you made. I'm using the Reverse Proxy productively now with multiple (custom) wildcard domains and multiple subdomains for all kinds of complicated setups with customers, like Exchange Server proxying and websocket applications etc...

The usecases that you gave me where exactly the right direction of what was needed, also for my usecases. I hope you can try it soon and give me feedback. I wish you happy holidays. :)

**Comment by gspannu** [comment]
Apologies... I never came back to you on testing and usage.

I was caught up in a few things and only started using this last week. have tested it quite extensively for handles using custom certificates.

**It works exactly as designed 👍** 

**_Many thanks... really appreciated._**
