### ISSUE TITLE
Support desec.io as a DNS provider (dedyn.io)

### ISSUE THREAD

**Issue by mirchiseth** [Monviech/os-caddy-plugin#75]
desec.io is another choice for a dns provider. It would be great if you can support them as well. Domains created with desec.io are of the format 
xxx.dedyn.io. 

You can find their docs at 

https://desec.readthedocs.io/en/latest/ 

Thanks.

**Comment by Monviech** [comment]
Can you tell me (or test) if this plugin supports this configuration scheme?

https://github.com/caddy-dns/desec

tls {
	dns desec 38372628276
}

Where the number is the ```Token```.

**Comment by Monviech** [comment]
@mirchiseth Just to be sure, do you mean TLS DNS-01 challenge, or do you mean dynamic-dns?

https://caddyserver.com/docs/modules/dynamic_dns

**Comment by mirchiseth** [comment]
I meant ACME DNS-01 challange and not the dynamic dns.

**Comment by Monviech** [comment]
Added in https://github.com/Monviech/os-caddy-plugin/pull/79
