### ISSUE TITLE
Include dynamic dns feature

### ISSUE THREAD

**Issue by Monviech** [Monviech/os-caddy-plugin#77]
https://github.com/mholt/caddy-dynamicdns

It can use the configured dns-provider and api key to dynamically update the dns records.

That means, any user of Caddy in the Opnsense won't need ddclient, caddy will provide that functionality for all provided DNS Providers automatically.

- [x] Create a new View Partial that puts the Dynamic DNS and the DNS Provider into a new view in general settings.
- [x] Compile module into caddy binary
- [x] Global Option - Dynamic DNS - Ipv4/Ipv6 (default), or Ipv6 only or Ipv4 only.
- [x] Global Option - Check Interval (If no option default is 1 hour)
- [x] Global Option - TTL of DNS Records
- [x] Global Option - IP Source "simple_http" - (example https://icanhazip.com) - One entry URL field.
- [x] Global Option - IP Source "interface" - manually set the interface name to read the IP address from. Example "igb1, igc1..."
- [x] New checkbox for domain and subdomain to enable dynamic dns.
- [x] Template Magic in Caddyfile
- [x] Adjust API Search Function and View Bootgrid

dns-provider and api-token are already implemented due to the dns01 challenge option.

Example of the Global Options:

```
{
	dynamic_dns {
		provider cloudflare API_TOKEN
		domains {
			example.com @
			example.net @ sub1 sub2 sub3
		}
		ip_source simple_http https://icanhazip.com
		ip_source interface eth0
		check_interval 5m
		versions ipv4 ipv6
		ttl 1h
	}
}
```

**Comment by mirchiseth** [comment]
this looks like a great enhancement as well. Right now I use ddclient in opnsense but if this functionality is built in the plugin it would remove one plugin.

**Comment by Monviech** [comment]
@mirchiseth When you can, please test the new version and features and give feedback if it works.

**Comment by mirchiseth** [comment]
Thanks. I updated the plugin and it works. I was able to stop the Dynamic DNS service and just use your plug in.

**Comment by Monviech** [comment]
@mirchiseth Awesome :) thanks for the feedback.
