### ISSUE TITLE
Configuration of HTTP_PORT would be nice

### ISSUE THREAD

**Issue by GrumpyMeow** [Monviech/os-caddy-plugin#87]
I'm trying to use this plugin. The first thing i'm now running into is, that i have to modify the port of the opnsense gui from port 80 to another port. This to make the port available for the ACME-challenge. I've made this change.

If it would be possible to specify the HTTP_PORT for Caddy this would be convenient. If this would be possible, i could use the port-forward of my modem to forward port 80 to the specified HTTP_PORT.

https://caddyserver.com/docs/json/apps/http/http_port/

**Comment by Monviech** [comment]
Hello, thanks for trying the plugin.

I've read about this in the documentation, and Caddy will always listen on 80 and 443 for clients. The default ports for clients can't be changed.

https://caddyserver.com/docs/caddyfile/options#http-port
https://caddyserver.com/docs/caddyfile/options#https-port

**Comment by Monviech** [comment]
Since there are many options to get certificates in Caddy, I will put this on won't fix.
