### ISSUE TITLE
Rename service in Services dashboard widget

### ISSUE THREAD

**Issue by pmhausen** [Monviech/os-caddy-plugin#92]
Given that the web server function is rather neglected and the plugin serves as a reverse proxy exclusively I suggest renaming the Services widget entry from "Caddy Web Server" to "Caddy Reverse Proxy".

**Comment by Monviech** [comment]
I cant do that, I'm using their official names:

https://github.com/caddyserver/caddy?tab=readme-ov-file#about

**Comment by pmhausen** [comment]
Then rename it to just "Caddy". :)

**Comment by Monviech** [comment]
I'll put this on the list and ponder more about it. There's a lot of documentation that would need to be adjusted. Also, there are a few other spots where I use this name. Right now, the functionality isn't really affected by it, so I'll keep the name for now until there's the right opportunity.

**Comment by pmhausen** [comment]
Not important, was just an idea. I don't really mind if you close it as "won't fix".

**Comment by Monviech** [comment]
I'll put this on won't fix for now.
