### ISSUE TITLE
OPNSense & Caddy & traccar

### ISSUE THREAD

**Issue by jemkewl** [Monviech/os-caddy-plugin#97]
newbie here, but trying to learn -

Caddy appears to be working well via the configuration within the OPNsense UI to expose an internal server hosting traccar.

By going to traccar.mydomain.com from the Internet, the manager is served successfully.  The manager website works well.

A client application makes http based requests to share GPS information.  It does this via a POST vs a GET.
Is Caddy able to work with this type of configuration?

Within the logs of Caddy, this is seen (scrubbed details):
	"info","ts":"2024-02-18T18:27:25Z","logger":"http.log.access.5564f6a8-789f-4797-9148-2156943d5128","msg":"handled request","request":{"remote_ip":"166.xxx.xxx.xxx","remote_port":"64896","client_ip":"166.xxx.xxx.xxxx","proto":"HTTP/1.1","method":"POST","host":"traccar.mydomain.com","uri":"/?id=12345&timestamp=1708280659&lat=xx.181772&lon=-xx.5044574&speed=0.0&bearing=0.0&altitude=xx.70000076293945&accuracy=100.0&batt=68.0","headers":{"User-Agent":["Dalvik/2.1.0 (Linux; U; Android 13; SM-N986U1 Build/TP1A.220624.014)"],"Connection":["keep-alive"],"Accept-Encoding":["gzip"],"Content-Length":["0"],"Via":["HTTP/1.1 zway2amcuc01ism001.wnsnet.attws.com"],"Content-Type":["application/x-www-form-urlencoded"]}},"bytes_read":0,"user_id":"","duration":0.000040073,"size":0,"status":308,"resp_headers":{"Server":["Caddy"],"Connection":["close"],"Location":["https://traccar.mydomain.com/?id=12345&timestamp=1708280659&lat=xx.181772&lon=-xx.5044574&speed=0.0&bearing=0.0&altitude=xx.70000076293945&accuracy=100.0&batt=68.0"],"Content-Type":[]}}

**Comment by Monviech** [comment]
Hey there, I would ask in the https://caddy.community about that.

They have a help template, you can reuse most infos that are here when I had a question in the past: https://caddy.community/t/logging-transformation-formatting-help/22259

Your current built is here: https://github.com/Monviech/os-caddy-plugin/blob/main/usr/local/bin/README.md#current-build

You can get your current Caddyfile with: cat /usr/local/etc/caddy/Caddyfile

**Comment by jemkewl** [comment]
Thank you!

**Comment by Monviech** [comment]
@jemkewl Got it all sorted out?

**Comment by jemkewl** [comment]
Yes!

It started working without any changes (that I know I did) - wondering if maybe I had to hit apply at the general settings VS the reverse proxy screen or restarting the service in opnsense - really don't know what change occurred, but working well.

Appreciate following up. Now have 1 public facing and multiple internal only facing "sites" with SSL offloading.

**Comment by Monviech** [comment]
Great you got it working.

The apply button in general is different than the one in reverse proxy. In general, it also "saves" the general form. If you swap screens without pressing apply there, your changes get lost.

Also, install the latest version of the plugin, there's additional validations now, it's an important update.

Have a good day. ^^

**Comment by jemkewl** [comment]
Thanks! You as well.

Looking forward to your continued integration!
